/**
 * GCAT/catalog country-code → display-name map.
 *
 * The catalog uses GCAT "state" codes: mostly ISO-3166 alpha-2, plus legacy
 * vehicle-plate style codes (D = Germany, J = Japan, F = France...), historic
 * entities (SU, CSSR), and multi-national organisations (I-ESA, I-EU, CIS...).
 *
 * Shared so the catalog page can reuse it. Unknown codes fall back to the raw
 * code — the URL/API contract stays raw codes throughout.
 */
export const COUNTRY_NAMES: Record<string, string> = {
  // Major players & legacy single-letter plate codes
  US: "United States",
  SU: "Soviet Union",
  RU: "Russia",
  CIS: "Commonwealth of Independent States",
  CN: "China",
  PRC: "China (PRC)",
  F: "France",
  J: "Japan",
  JPN: "Japan",
  UK: "United Kingdom",
  IN: "India",
  IND: "India",
  D: "Germany",
  I: "Italy",
  E: "Spain",
  L: "Luxembourg",
  N: "Norway",
  S: "Sweden",
  B: "Belgium",
  T: "Thailand",
  P: "Portugal",
  POR: "Portugal",
  // Multi-national organisations
  "I-ESA": "European Space Agency",
  "I-ESRO": "European Space Research Organisation",
  "I-EU": "European Union",
  "I-EUM": "EUMETSAT",
  "I-EUT": "Eutelsat",
  "I-INT": "Intelsat",
  "I-INM": "Inmarsat",
  "I-ARAB": "Arabsat",
  "I-NATO": "NATO",
  "I-RASC": "RascomStar",
  // Historic entities
  CSSR: "Czechoslovakia",
  CSFR: "Czechoslovakia (CSFR)",
  HKUK: "Hong Kong (British)",
  // Everyone else
  AM: "Armenia",
  AO: "Angola",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  AZ: "Azerbaijan",
  BD: "Bangladesh",
  BGN: "Bulgaria",
  BGR: "Bulgaria",
  BH: "Bahrain",
  BM: "Bermuda",
  BO: "Bolivia",
  BR: "Brazil",
  BT: "Bhutan",
  BW: "Botswana",
  BY: "Belarus",
  CA: "Canada",
  CH: "Switzerland",
  CL: "Chile",
  CO: "Colombia",
  CR: "Costa Rica",
  CYM: "Cayman Islands",
  CZ: "Czechia",
  DJ: "Djibouti",
  DK: "Denmark",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  ET: "Ethiopia",
  FI: "Finland",
  GH: "Ghana",
  GR: "Greece",
  GT: "Guatemala",
  HK: "Hong Kong",
  HR: "Croatia",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IR: "Iran",
  IRAN: "Iran",
  JO: "Jordan",
  KE: "Kenya",
  KP: "North Korea",
  KR: "South Korea",
  SKOR: "South Korea",
  KW: "Kuwait",
  KZ: "Kazakhstan",
  LA: "Laos",
  LK: "Sri Lanka",
  LT: "Lithuania",
  LV: "Latvia",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MN: "Mongolia",
  MU: "Mauritius",
  MX: "Mexico",
  MY: "Malaysia",
  MYM: "Myanmar",
  NG: "Nigeria",
  NL: "Netherlands",
  NP: "Nepal",
  NZ: "New Zealand",
  OM: "Oman",
  PE: "Peru",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PR: "Puerto Rico",
  PY: "Paraguay",
  QA: "Qatar",
  RO: "Romania",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SD: "Sudan",
  SG: "Singapore",
  SI: "Slovenia",
  SK: "Slovakia",
  SN: "Senegal",
  TN: "Tunisia",
  TR: "Türkiye",
  TW: "Taiwan",
  UA: "Ukraine",
  UAE: "United Arab Emirates",
  UG: "Uganda",
  UY: "Uruguay",
  VE: "Venezuela",
  VN: "Vietnam",
  ZA: "South Africa",
  ZW: "Zimbabwe",
  TBD: "Undetermined",
};

/** Full display name for a catalog country code, or null if unknown. */
export function countryName(code: string | null | undefined): string | null {
  if (!code) return null;
  return COUNTRY_NAMES[code.toUpperCase()] ?? null;
}

/** "Germany (D)" style label; falls back to the raw code for unknown values. */
export function countryLabel(code: string | null | undefined): string {
  if (!code) return "—";
  const name = countryName(code);
  return name ? `${name} (${code})` : code;
}
